export const browserCoreExamples = [
  "mayros browser status",
  "mayros browser start",
  "mayros browser stop",
  "mayros browser tabs",
  "mayros browser open https://example.com",
  "mayros browser focus abcd1234",
  "mayros browser close abcd1234",
  "mayros browser screenshot",
  "mayros browser screenshot --full-page",
  "mayros browser screenshot --ref 12",
  "mayros browser snapshot",
  "mayros browser snapshot --format aria --limit 200",
  "mayros browser snapshot --efficient",
  "mayros browser snapshot --labels",
];

export const browserActionExamples = [
  "mayros browser navigate https://example.com",
  "mayros browser resize 1280 720",
  "mayros browser click 12 --double",
  'mayros browser type 23 "hello" --submit',
  "mayros browser press Enter",
  "mayros browser hover 44",
  "mayros browser drag 10 11",
  "mayros browser select 9 OptionA OptionB",
  "mayros browser upload /tmp/mayros/uploads/file.pdf",
  'mayros browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mayros browser dialog --accept",
  'mayros browser wait --text "Done"',
  "mayros browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mayros browser console --level error",
  "mayros browser pdf",
];
