#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${MAYROS_INSTALL_E2E_IMAGE:-${MAYROS_INSTALL_E2E_IMAGE:-mayros-install-e2e:local}}"
INSTALL_URL="${MAYROS_INSTALL_URL:-${MAYROS_INSTALL_URL:-https://mayros.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
MAYROS_E2E_MODELS="${MAYROS_E2E_MODELS:-${MAYROS_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e MAYROS_INSTALL_URL="$INSTALL_URL" \
  -e MAYROS_INSTALL_TAG="${MAYROS_INSTALL_TAG:-${MAYROS_INSTALL_TAG:-latest}}" \
  -e MAYROS_E2E_MODELS="$MAYROS_E2E_MODELS" \
  -e MAYROS_INSTALL_E2E_PREVIOUS="${MAYROS_INSTALL_E2E_PREVIOUS:-${MAYROS_INSTALL_E2E_PREVIOUS:-}}" \
  -e MAYROS_INSTALL_E2E_SKIP_PREVIOUS="${MAYROS_INSTALL_E2E_SKIP_PREVIOUS:-${MAYROS_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
